name: Release
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        required: true
        description: "Where to release"
        options: [staging, canary, prod]

permissions:
  contents: read
  packages: write
  deployments: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v4

      # Compute a LOWERCASE image ref like ghcr.io/<owner>/<repo>
      - name: Normalize image ref to lowercase
        id: img
        shell: bash
        run: |
          REPO="${{ github.repository }}"             # e.g. Sasageyo1230/rika-guardrail
          REPO_LC="$(echo "$REPO" | tr '[:upper:]' '[:lower:]')"   # sasageyo1230/rika-guardrail
          echo "IMAGE_REF=ghcr.io/${REPO_LC}" >> "$GITHUB_ENV"
          echo "SHA_TAG=${GITHUB_SHA}"    >> "$GITHUB_ENV"
          echo "ENV_TAG=${{ inputs.env }}" >> "$GITHUB_ENV"

      - uses: docker/setup-buildx-action@v3

      # Login with GITHUB_TOKEN (works for personal repos). If your org blocks this, add a GHCR_PAT secret and use it instead.
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT || secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          provenance: false
          tags: |
            ${{ env.IMAGE_REF }}:${{ env.SHA_TAG }}
            ${{ env.IMAGE_REF }}:${{ env.ENV_TAG }}
