name: Release
on:
  workflow_dispatch:
    inputs:
      env:
        type: choice
        required: true
        description: "Where to release"
        options: [staging, canary, prod]

permissions:
  contents: read
  packages: write
  deployments: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/rika-guardrail:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/rika-guardrail:${{ inputs.env }}

  # Optional canary health + auto-revert you can wire later once CANARY_URL exists
